language: smalltalk
sudo: false
smalltalk:
  - Pharo-6.0
  - Pharo-5.0
  - Pharo-4.0
  - Pharo-3.0
  - Squeak-5.1
  - GemStone-3.1.0.6
  - GemStone-3.2.16
  - GemStone-3.3.4
cache:
  directories:
    - $SMALLTALK_CI_CACHE
#matrix:
#  allow_failures:
#    - smalltalk: Pharo-6.0
